### ISSUE TITLE
Build failure for util-linux 2.40.4 with glibc 2.41

### ISSUE THREAD

**Issue by johnny-mnemonic** [linux-ia64/glibc-ia64#9]
util-linux 2.40.4 fails to build with glibc 2.41 at c1f2da81d81f72398cc5b0524edea0ec877529b3

```
14:22:57 136/438 Building 2-base/util-linux (2.40.4) ~10s
  Reading build/.../cross/lib/pkg_util-linux_post.conf
  Building in src.util-linux.ia64.250213.142257.8641, with 16 threads
  Writing output to $root/var/adm/logs/2-util-linux.out
!   CCLD     setterm
! /srv/t2/build/ia64-25.2-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2 ..
! <artificial>:(.text+0x6c52): undefined reference to `round'
```

**Comment by johnny-mnemonic** [comment]
This seems to be due to https://github.com/linux-ia64/glibc-ia64/commit/298605475cf893289effdee084cc68fcf1f92459 which keeps `libm_alias_*_other` instead of exchanging it for `libm_alias_*` like it is done in https://sourceware.org/git/?p=glibc.git;a=commit;h=52c512bc56ed99e9ddc3efe98e3433016016c69a back in 2021.

**Comment by johnny-mnemonic** [comment]
This is now fixed in:
* https://github.com/linux-ia64/glibc-ia64/tree/master-w-ia64
* https://github.com/linux-ia64/glibc-ia64/tree/master-epic
* https://github.com/linux-ia64/glibc-ia64/tree/release/2.41/master-w-ia64
* https://github.com/linux-ia64/glibc-ia64/tree/release/2.41/master-epic

**Comment by johnny-mnemonic** [comment]
Another related historic commit: https://github.com/linux-ia64/glibc-ia64/commit/0609ec0a74f6360ebfb45d048f071a75dfcbc6c7

Definitions of `libm_alias*` here:
* https://github.com/linux-ia64/glibc-ia64/blob/master-w-ia64/sysdeps/generic/libm-alias-float.h
* https://github.com/linux-ia64/glibc-ia64/blob/master-w-ia64/sysdeps/generic/libm-alias-double.h
* https://github.com/linux-ia64/glibc-ia64/blob/master-w-ia64/sysdeps/generic/libm-alias-ldouble.h
